///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAll = 'assets/images/all.png';
  static const String imagesApp1 = 'assets/images/app1.jpeg';
  static const String imagesAppbar = 'assets/images/appbar.png';
  static const String imagesBg = 'assets/images/bg.png';
  static const String imagesBg1 = 'assets/images/bg1.png';
  static const String imagesBg2 = 'assets/images/bg2.svg';
  static const String imagesCofirm = 'assets/images/cofirm.png';
  static const String imagesConfirm2 = 'assets/images/confirm2.png';
  static const String imagesEasy = 'assets/images/easy.png';
  static const String imagesFast = 'assets/images/fast.png';
  static const String imagesFree = 'assets/images/free.png';
  static const String imagesLogin = 'assets/images/login.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesResetpass = 'assets/images/resetpass.png';
  static const String imagesSave = 'assets/images/save.png';
}
