name: application_aqars
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: "none" # Remove this line if you wish to publish to pub.dev.

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

# Dependencies required for your Flutter project.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  animated_bottom_navigation_bar: ^1.3.3
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.0.6
  google_sign_in: ^6.2.1
  http: ^1.2.2   # Added space after the colon
  dio: ^5.7.0
  share_plus: ^6.0.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings.
flutter:
  uses-material-design: true

  # Assets used in your project.
  assets:
    - assets/images/

  # Fonts used in your project.
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700
